### ISSUE TITLE
Code Walkthrough

### ISSUE THREAD

**Issue by hhslepicka** [NSLS-II/amostra#2]
@arkilic and I are going over Amostra locally and here are the bugs/improvements needed:

- [x] : Allow the sample name to be updated. Sometimes a typo happens and we need to fix it.
- [x] : Create a log file for the erros on the server side.
- [x] : Get rid of the local sample name lookup as a result to the first change needed.

To be continued...

**Comment by arkilic** [comment]
Commit 928feb45858e251c6bc1fbe17b4ff610eb8c4dd6 takes care of box 1
Do you still need python 2.7 compatibility on the client side?

**Comment by hhslepicka** [comment]
@arkilic Yes, we still need py27 compatibility on the client side.

**Comment by arkilic** [comment]
Okay, closing this to open new issues @hhslepicka

**Comment by hhslepicka** [comment]
No problem! :+1:

On Mon, Mar 14, 2016 at 10:47 AM, Arman Arkilic <notifications@github.com>
wrote:

> Okay, closing this to open new issues @hhslepicka
> <https://github.com/hhslepicka>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NSLS-II/amostra/issues/2#issuecomment-196345961>.
>



-- 
Hugo Slepicka
*hhslepicka@gmail.com <hhslepicka@gmail.com>*
*+1 631 855 5717*
