### ISSUE TITLE
ENH: reference files

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/amostra#29]
I would like a way to reference files in amostra using filestore. This way we can load data associated with the sample. eg. keep a couple of potential atomic structures with the sample so that we can compare the the theoretical structure against the observed x-ray data.

**Comment by arkilic** [comment]
All amostra documents are flexible, so you can create a file reference on the fly. If you are doing a lot of searches on these filenames, I can sparsely index this field for you.

**Comment by CJ-Wright** [comment]
I think this kinda goes with [databroker/74](https://github.com/NSLS-II/databroker/issues/74).
The main thing is having auto-retrieve of the file from filestore on getting the sample.

**Comment by arkilic** [comment]
If you want an auto-retrieve method, this is an issue for databroker as you said. An alternative trick to create this relationship would be making filestore instance reference to a sample or add the sample information to mds. The direction of the foreign-key is something we need to decide with @tacaswell

**Comment by CJ-Wright** [comment]
In talking with @danielballan we discussed having the sample uid in the mds header as an external resource, then unpacking recursively the external resources. This would first unpack the sample information into the returned "header " and then unpack the filestore info which was stored in the sample info.

**Comment by arkilic** [comment]
Can a sample generate more than one file?

**Comment by danielballan** [comment]
@CJ-Wright is talking about putting references to external data (managed by filestore) into amostra documents. The samples are generating files; they are containing references to (yes, potentially more than one) file. Is there something like `data_keys: {'foo': {'external': 'FILESTORE:...', ...}, ...}` in amostra that he could use for this?

**Comment by danielballan** [comment]
For those following by email, I edited my previous comment to fix a very confusing typo.

**Comment by arkilic** [comment]
I understand what he is talking about. I am trying to understand whether it is a one to many relationship or not. 
Of course, as I said in my very first comment, it is a **flexible document**, he can do it right now but it is not enforced or indexed.

**Comment by CJ-Wright** [comment]
I don't usually think of the files as generated by the sample, more just associated, but yes there could be multiple files associated with a sample.

**Comment by arkilic** [comment]
In this context, it doesn't matter whether they are related or generated by
