### ISSUE TITLE
Package installation not working

### ISSUE THREAD

**Issue by hhslepicka** [NSLS-II/amostra#3]
Fix the setup.py so I can use the :package:  in my tests!

**Comment by arkilic** [comment]
setup.py doesn't work because I need to separate the client and server repos. I'll do that next week since this seems to be working fine

**Comment by hhslepicka** [comment]
So far so good! :+1:

**Comment by tacaswell** [comment]
This is another reason to keep the file-based version around (to be used as a mock implementation for testing other libraries).

**Comment by arkilic** [comment]
File implementation will be around. I've thought and done some work about this.
