### ISSUE TITLE
Document REST API with swagger

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/amostra#47]
A standard way to document REST APIs is with a swagger.io JSON file such as [this example](https://petstore.swagger.io/v2/swagger.json) which can then be used to generate [nice documentation](https://petstore.swagger.io/?_ga=2.185646889.1695356204.1578417044-1745016407.1578417044#/).

**Comment by danielballan** [comment]
The REST API in defined in https://github.com/NSLS-II/amostra/blob/1cb496fdb32e2a22df214459df1698009e769c71/amostra/handlers.py#L55-L64

**Comment by ke-zhang-rd** [comment]
close by #49
