### ISSUE TITLE
Set up doctr

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/amostra#48]
The documentation at https://nsls-ii.github.io/amostra is out of date. Follow https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-docs.html to set up doctr.

The deploy command should be slightly different than the one in that documentation, though, because we publish to an _orgnaization_ repo, NSLS-II/NSLS-II.github.io. The command should be:

```
doctr deploy --deploy-repo NSLS-II/NSLS-II.github.io --deploy-branch-name master amostra;
```

The link in the README, which currently points to my personal fork, should also be updated.

**Comment by danielballan** [comment]
Thanks to @ke-zhang-rd for noticing this.

**Comment by ke-zhang-rd** [comment]
Close by #50
