### ISSUE TITLE
Issue about recursion triggered

### ISSUE THREAD

**Issue by ke-zhang-rd** [NSLS-II/amostra#51]
This issue is continue discuss of https://github.com/NSLS-II/amostra/pull/44. But it should be readable independently.
Usually Sample could create object successfully like scenario below.

**Success**
```
>>> from amostra.objects import Sample
>>> foo = Sample(None, name='abc')
>>> foo

Sample(composition='', description='', name='abc', projects=[], tags=[])
```

**Failure**
However,  if `name` is empty string `''`, recursion will be triggered. This was pointed by @tacaswell and I just copy past code here

```
>>> from amostra.objects import Sample
>>> foo = Sample(None, name='')
>>> foo

***Recursion maximum triggered
```

This issue tries to explain the details under the hood, but before there are some tips
**Tips**

- Here are two types of attributes involved. `compositioin`, `description` and `name` are `Unicode` which is raw type. `projects` and `tags` are `List` which inherent from `Instance` in traitlets. 
- When `Sample.__get__` is called, traitlets tries to get the value from `Sample._trait_values` which is a dict of `attribute_name: attribute_value`. If except, it tries to be smart to help you figure out(including call dynamic default to help you).
-   [`_validate`](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L587) function
```
    def _validate(self, obj, value):
        if value is None and self.allow_none:
            return value
        if hasattr(self, 'validate'):
            value = self.validate(obj, value)
        if obj._cross_validation_lock is False:
            value = self._cross_validate(obj, value)
        return value
```
**Pipelines of success scenario**

1. Initial default value or raw type(Unicode here) by `traitlets` which is empty string `''` [here](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L2042)
2. try to set argument to name by user's code, here set `name='abc'`
3. if past_value == value:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skip validation
    else:
          &nbsp;&nbsp;&nbsp;&nbsp;with [`self.hold_trait_notifications` ](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L994)
          &nbsp;&nbsp;&nbsp;&nbsp;# set [_cross_validation_lock](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L1103) = True when `__enter__` and set it back to False when `__exit__`
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. call user defined validation function, in amostra, it is [`_validate_with_jsonschema`](https://github.com/NSLS-II/amostra/blob/master/amostra/objects.py#L18)
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. `_validate_with_jsonschema` invokes [`to_dict`](https://github.com/NSLS-II/amostra/blob/master/amostra/objects.py#L55) method which will call [`get`](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L526) for all attributes.
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. traitlets find that ``projects`` wasn't initialized in [here](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L529)(not exist in `foo._trait_values`), it end up to call [dynamic default](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L1698) method to generate default value.
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. pass this dynamic default value to  [`_validate`](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L587) function
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. since `_cross_validation_lock` == True, **SKIP** `self._cross_validate`
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. return value and finish `self._trait_values['projects'] = value`

**Pipelines of failure scenario**
```
>>> foo
***Recursion maximum triggered
```

1. run [`__repr__`](https://github.com/NSLS-II/amostra/blob/master/amostra/objects.py#L49), 
2. it eventually call `__get__` then `get` method for all attributes
3. traitlets find that `'projects'` wasn't initialized in [here](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L529)(not exist in `foo._trait_values`), it's call [dynamic_default](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L1698) method to generate default value.
4. pass this dynamic default value to   [`_validate`](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L587) function
5. `since _cross_validation_lock` == False, **RUN** `self._cross_validate`
6. `self._cross_validate` will trigger user defined validation function which is `_validate_with_jsonschema`
7. Our `_validate_with_jsonschema` invoke `to_dict` method which actually called `__get__` for all attributes.
8. Goto 2 (Infinity loop build)

**Solution**(has been implement in #52)
The solution could be using a [`cross_validation_lock`](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L1049) contextmanager to control steps 5 to break loop.

1. run `__repr__`, 
   with self.cross_validation_lock:
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. it calls `__get__` method for all attributes
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. traitlets find that `'projects'` wasn't initialized(not exist in `foo._trait_values`),it's call dynamic default method to generate default value.
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. pass this dynamic default value to [`_validate`](https://github.com/ipython/traitlets/blob/4.3.x/traitlets/traitlets.py#L587) function
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. since `_cross_validation_lock == False` in context, **SKIP** self._cross_validate
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. return value and finish `self._trait_values['projects'] = value`

**Comment by ke-zhang-rd** [comment]
@danielballan 
@tacaswell 
comments/concerns/suggestions?

**Comment by tacaswell** [comment]
Is this fixed now?

**Comment by ke-zhang-rd** [comment]
This is fixed. 
mainly by https://github.com/NSLS-II/amostra/pull/52/files#diff-44f05067fc32a294f8f47b5a4e1e781bR50
